
{ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
 บ                                                                          บ
 บ     Sibyl Portable Component Classes                                     บ
 บ                                                                          บ
 บ     Copyright (C) 1995,97 SpeedSoft Germany,   All rights reserved.      บ
 บ                                                                          บ
 ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ}

Unit Language;

{ define Compiler symbol gr to include German Resource file.
  otherwise the Default (English) Resource file will be used. }

{ $DEFINE gr}

{$IFDEF gr}
  {$R German}
{$ELSE gr}
  {$R English}
{$ENDIF gr}


Interface


Implementation

End.


