
CONST {Buttons.SRF}
    StdBmpOk         =25500;
    StdBmpCancel     =25501;
    StdBmpHelp       =25502;
    StdBmpYes        =25503;
    StdBmpNo         =25504;
    StdBmpClose      =25505;
    StdBmpAbort      =25506;
    StdBmpRetry      =25507;
    StdBmpIgnore     =25508;
    StdBmpAll        =25509;
    StdBmpOpen       =25510;
    StdBmpAsk        =25515;
    StdBmpHand       =25516;
    StdBmpInfo       =25517;
    StdBmpProp       =25518;


CONST {MMedia.SRF}
    StdBmpPlay       =25520;
    StdBmpPause      =25521;
    StdBmpRewind     =25522;
    StdBmpStop       =25523;
    StdBmpPlay1      =25524;
    StdBmpPlay2      =25525;
    StdBmpPlay3      =25526;
    StdBmpRecord     =25527;
    StdBmpRecord1    =25528;
    StdBmpNextTrk    =25529;
    StdBmpPrevTrk    =25530;
    StdBmpBackTrk    =25531;
    StdBmpStepTrk    =25532;
    StdBmpEject      =25533;


CONST {DBCtrls.SRF}
    StdBmpDBFirst    =25540;
    StdBmpDBPrior    =25541;
    StdBmpDBNext     =25542;
    StdBmpDBLast     =25543;
    StdBmpDBInsert   =25544;
    StdBmpDBDelete   =25545;
    StdBmpDBEdit     =25546;
    StdBmpDBPost     =25547;
    StdBmpDBCancel   =25548;
    StdBmpDBRefresh  =25549;


CONST {TabCtrls.SRF}
    StdBmpEdgeTop         =25560;
    StdBmpEdgeTopPlus     =25561;
    StdBmpEdgeTopMinus    =25562;
    StdBmpEdgeBottom      =25563;
    StdBmpEdgeBottomPlus  =25564;
    StdBmpEdgeBottomMinus =25565;


